### ISSUE TITLE
Sometimes adding new playlists causes the custom theme to break

### ISSUE THREAD

**Issue by marutypes** [marutypes/FoundryVTT-Maru-Combat-Themes#2]
See title

**Comment by TJourney** [comment]
This appears to be related to the mapping of playlists in getPlaylists() and the re-ordering of Playlists which takes place when client reloads - causing a mismatch of the playlist index across sessions. My observations are that when a new playlist is added, it tends to be added as the last element of the Playlists array - but when the client reloads the Playlists array is generated in alphabetical order. The settings have saved their values from the previous index values, which now correspond to different playlists.

**Comment by marutypes** [comment]
I believe you're right about the cause! I've been meaning to come back and fix this (I've hit it a few times in my own games), but if you want to take a crack at it I'd be happy to accept a PR. I think we can probably do some kind of map of the playlist names or something, and update our indexes from that on load?

**Comment by marutypes** [comment]
Fixed in https://github.com/marutypes/FoundryVTT-Maru-Combat-Themes/commit/57087c1606579ac2d09d68900e3c3a8f838e28c6
